import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import axios from "axios";

export const getServerSideProps = async () => {
  const res = await fetch("https://api.zoom.us/v2/users/me/meetings", {
    headers: {
      Authorization: `Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6Ijc2Y2VtVC1FUWEtSDdHSm01SkdFVWciLCJleHAiOjE2Mjc4NDQ0MDAsImlhdCI6MTYyNTUzNjQ2MH0.nHpNYt8wRcAmPxHLVgDyNYVcnWOYkQLMQs1As7YNU9o`,
    },
  });
  const data = await res.json();
  return {
    props: {
      meetings: data.meetings,
    },
  };
};

export default function Home({ meetings }) {
  return (
    <>
      <Head>
        <title>Synthesis Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/synthesis-logo.svg" />
      </Head>
      <NavBar />
      <section className={styles.main}>
        <div className={styles.header}>
          <h1>Classes for cohort: Syn5</h1>
          {/* Syn5 is a hypothetical cohort name :) */}
          <button className={styles.startMeetingBtn}>Create meeting</button>
        </div>

        {meetings.map((meeting) => (
          <div className={styles.classes} key={meeting.id}>
            <h2 className={styles.meetingTopic}>{meeting.topic}</h2>
            <div className={styles.meetingDetails}>
              <div className={styles.meetingTime}>
                <h3 className={styles.title}>{meeting.duration} minutes</h3>
              </div>
              <div className={styles.meetingDate}>
                <h3 className={styles.title}>
                  {meeting.start_time.slice(0, meeting.start_time.search("T"))}
                </h3>
              </div>
            </div>
            <Link href={meeting.join_url}>
              <a rel="noopener noreferrer" target="_blank">
                <button className={styles.joinBtn}>Join!</button>
              </a>
            </Link>
          </div>
        ))}
      </section>
    </>
  );
}

// could've implemented e.preventDefault for more smooth experience (no page refresh)
// the tradeoff is that the new meeting wont automatically render in the meeting list when new meeting is created since I am using getServerSideProps()
// the other option I could've take would be to use getStaticProps(), implement e.preventDefault and
// use unstable_revalidate: for example 1 second that way we have the smooth experience of no page refresh and automatic new meeting added to the meeting list
